apiVersion: v1
kind: ConfigMap
metadata:
  name: localstack-config
  namespace: localstack
data:
  init-aws.sh: |
    #!/bin/bash
    set -e
    
    echo "Waiting for LocalStack to be ready..."
    while ! curl -s http://localstack.localstack.svc.cluster.local:4566/_localstack/health > /dev/null; do
      sleep 2
    done
    echo "LocalStack is ready!"
    
    # Create example S3 buckets
    aws --endpoint-url=http://localstack.localstack.svc.cluster.local:4566 s3 mb s3://app-data || true
    aws --endpoint-url=http://localstack.localstack.svc.cluster.local:4566 s3 mb s3://app-config || true
    aws --endpoint-url=http://localstack.localstack.svc.cluster.local:4566 s3 mb s3://app-logs || true
    aws --endpoint-url=http://localstack.localstack.svc.cluster.local:4566 s3 mb s3://app-artifacts || true

    # Create example SQS queues
    aws --endpoint-url=http://localstack.localstack.svc.cluster.local:4566 sqs create-queue --queue-name app-events || true
    aws --endpoint-url=http://localstack.localstack.svc.cluster.local:4566 sqs create-queue --queue-name app-dlq || true
    aws --endpoint-url=http://localstack.localstack.svc.cluster.local:4566 sqs create-queue --queue-name app-processing || true

    # Create example SNS topics
    aws --endpoint-url=http://localstack.localstack.svc.cluster.local:4566 sns create-topic --name app-alerts || true
    aws --endpoint-url=http://localstack.localstack.svc.cluster.local:4566 sns create-topic --name app-notifications || true

    echo "LocalStack initialization complete!"
  
  aws-config: |
    [default]
    region = us-east-1
    output = json
  
  aws-credentials: |
    [default]
    aws_access_key_id = test
    aws_secret_access_key = test