apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack
  namespace: localstack
  labels:
    app: localstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: localstack
  template:
    metadata:
      labels:
        app: localstack
    spec:
      containers:
      - name: localstack
        image: localstack/localstack:latest
        ports:
        - containerPort: 4566
          name: edge
        - containerPort: 4510
          name: admin
        env:
        - name: SERVICES
          value: "s3,sqs,sns,dynamodb,lambda,cloudformation,iam,secretsmanager,ssm,rds"
        - name: DEBUG
          value: "1"
        - name: PERSISTENCE
          value: "0"
        - name: DOCKER_HOST
          value: "unix:///var/run/docker.sock"
        - name: DATA_DIR
          value: "/data"
        - name: HOSTNAME_EXTERNAL
          value: "localstack.localstack.svc.cluster.local"
        - name: SKIP_INFRA_DOWNLOADS
          value: "1"
        volumeMounts:
        - name: localstack-data
          mountPath: /data
        - name: docker-sock
          mountPath: /var/run/docker.sock
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi" 
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /_localstack/health
            port: 4566
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /_localstack/health
            port: 4566
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
      volumes:
      - name: localstack-data
        emptyDir: {}
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
          type: Socket