{{- if .Values.initJob.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "localstack.fullname" . }}-init
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "localstack.labels" . | nindent 4 }}
    app.kubernetes.io/component: init-job
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: aws-cli
        image: {{ .Values.initJob.image.repository }}:{{ .Values.initJob.image.tag }}
        imagePullPolicy: {{ .Values.initJob.image.pullPolicy }}
        command: ["/bin/bash", "/scripts/init-aws.sh"]
        env:
        - name: AWS_ACCESS_KEY_ID
          value: "test"
        - name: AWS_SECRET_ACCESS_KEY
          value: "test"
        - name: AWS_DEFAULT_REGION
          value: "us-east-1"
        volumeMounts:
        - name: init-scripts
          mountPath: /scripts
        - name: aws-config
          mountPath: /root/.aws
      volumes:
      - name: init-scripts
        configMap:
          name: {{ include "localstack.configMapName" . }}
          defaultMode: 0755
      - name: aws-config
        configMap:
          name: {{ include "localstack.configMapName" . }}
          items:
          - key: aws-config
            path: config
          - key: aws-credentials
            path: credentials
{{- end }}